using Finnova.Core.Models;
using Microsoft.EntityFrameworkCore;

namespace Finnova.Data.Seeds
{
    public static class BankSeed
    {
        public static void SeedBanks(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Banco>().HasData(
                new Banco { IdBanco = 1, Codigo = "001", Nome = "Banco do Brasil S.A.", Ativo = true },
                new Banco { IdBanco = 2, Codigo = "003", Nome = "Banco da Amazônia S.A.", Ativo = true },
                new Banco { IdBanco = 3, Codigo = "004", Nome = "Banco do Nordeste do Brasil S.A.", Ativo = true },
                new Banco { IdBanco = 4, Codigo = "021", Nome = "Banestes S.A. Banco do Estado do Espírito Santo", Ativo = true },
                new Banco { IdBanco = 5, Codigo = "025", Nome = "Banco Alfa S.A.", Ativo = true },
                new Banco { IdBanco = 6, Codigo = "033", Nome = "Banco Santander (Brasil) S.A.", Ativo = true },
                new Banco { IdBanco = 7, Codigo = "036", Nome = "Banco Bradesco BBI S.A.", Ativo = true },
                new Banco { IdBanco = 8, Codigo = "037", Nome = "Banco do Estado do Pará S.A.", Ativo = true },
                new Banco { IdBanco = 9, Codigo = "041", Nome = "Banco do Estado do Rio Grande do Sul S.A.", Ativo = true },
                new Banco { IdBanco = 10, Codigo = "047", Nome = "Banco do Estado de Sergipe S.A.", Ativo = true },
                new Banco { IdBanco = 11, Codigo = "070", Nome = "Banco de Brasília S.A. (BRB)", Ativo = true },
                new Banco { IdBanco = 12, Codigo = "104", Nome = "Caixa Econômica Federal", Ativo = true },
                new Banco { IdBanco = 13, Codigo = "184", Nome = "Banco Itaú BBA S.A.", Ativo = true },
                new Banco { IdBanco = 14, Codigo = "237", Nome = "Banco Bradesco S.A.", Ativo = true },
                new Banco { IdBanco = 15, Codigo = "260", Nome = "Nu Pagamentos S.A. (Nubank)", Ativo = true },
                new Banco { IdBanco = 16, Codigo = "318", Nome = "Banco BMG S.A.", Ativo = true },
                new Banco { IdBanco = 17, Codigo = "341", Nome = "Itaú Unibanco S.A.", Ativo = true },
                new Banco { IdBanco = 18, Codigo = "422", Nome = "Banco Safra S.A.", Ativo = true },
                new Banco { IdBanco = 19, Codigo = "623", Nome = "Banco PAN S.A.", Ativo = true },
                new Banco { IdBanco = 20, Codigo = "633", Nome = "Banco Rendimento S.A.", Ativo = true },
                new Banco { IdBanco = 21, Codigo = "652", Nome = "Itaú Unibanco Holding S.A.", Ativo = true },
                new Banco { IdBanco = 22, Codigo = "735", Nome = "Neon Pagamentos S.A.", Ativo = true },
                new Banco { IdBanco = 23, Codigo = "336", Nome = "C6 Bank S.A.", Ativo = true },
                new Banco { IdBanco = 24, Codigo = "077", Nome = "Banco Inter S.A.", Ativo = true },
                new Banco { IdBanco = 25, Codigo = "212", Nome = "Banco Original S.A.", Ativo = true },
                new Banco { IdBanco = 26, Codigo = "169", Nome = "Banco Olé Bonsucesso Consignado S.A.", Ativo = true },
                new Banco { IdBanco = 27, Codigo = "140", Nome = "Easynvest – Nubank Investimentos", Ativo = true },
                new Banco { IdBanco = 28, Codigo = "102", Nome = "XP Investimentos S.A.", Ativo = true },
                new Banco { IdBanco = 29, Codigo = "085", Nome = "Cooperativa Central de Crédito Urbano – Cecred", Ativo = true },
                new Banco { IdBanco = 30, Codigo = "099", Nome = "Uniprime Norte do Paraná", Ativo = true },
                new Banco { IdBanco = 31, Codigo = "756", Nome = "Sicoob – Sistema de Cooperativas de Crédito do Brasil", Ativo = true },
                new Banco { IdBanco = 32, Codigo = "748", Nome = "Sicredi – Sistema de Crédito Cooperativo", Ativo = true },
                new Banco { IdBanco = 33, Codigo = "654", Nome = "Banco Digimais (ex-Banco Renner)", Ativo = true },
                new Banco { IdBanco = 34, Codigo = "712", Nome = "Banco Ourinvest S.A.", Ativo = true },
                new Banco { IdBanco = 35, Codigo = "080", Nome = "BTG Pactual Digital", Ativo = true },
                new Banco { IdBanco = 36, Codigo = "197", Nome = "Stone Pagamentos S.A.", Ativo = true },
                new Banco { IdBanco = 37, Codigo = "389", Nome = "Banco Mercantil do Brasil S.A.", Ativo = true },
                new Banco { IdBanco = 38, Codigo = "473", Nome = "Banco Caixa Geral Brasil", Ativo = true },
                new Banco { IdBanco = 39, Codigo = "630", Nome = "Smartbank S.A.", Ativo = true },
                new Banco { IdBanco = 40, Codigo = "653", Nome = "Banco Indusval S.A. (Ibank)", Ativo = true },
                new Banco { IdBanco = 41, Codigo = "119", Nome = "Western Union do Brasil", Ativo = true },
                new Banco { IdBanco = 42, Codigo = "174", Nome = "Pefisa – Pernambucanas Financeira", Ativo = true },
                new Banco { IdBanco = 43, Codigo = "105", Nome = "Lecca Crédito Financiamento", Ativo = true },
                new Banco { IdBanco = 44, Codigo = "108", Nome = "Banco Marechal S.A.", Ativo = true },
                new Banco { IdBanco = 45, Codigo = "336", Nome = "Banco C6 Consignado S.A.", Ativo = true },
                new Banco { IdBanco = 46, Codigo = "655", Nome = "Banco Votorantim (BV)", Ativo = true },
                new Banco { IdBanco = 47, Codigo = "746", Nome = "Banco Modal S.A.", Ativo = true },
                new Banco { IdBanco = 48, Codigo = "413", Nome = "Banco BV Financeira", Ativo = true },
                new Banco { IdBanco = 49, Codigo = "369", Nome = "Banco CSF S.A. (Carrefour)", Ativo = true },
                new Banco { IdBanco = 50, Codigo = "364", Nome = "Banco Bradescard S.A.", Ativo = true },
                new Banco { IdBanco = 51, Codigo = "081", Nome = "Banco Seguro S.A.", Ativo = true },
                new Banco { IdBanco = 52, Codigo = "082", Nome = "Banco Topázio S.A.", Ativo = true },
                new Banco { IdBanco = 53, Codigo = "083", Nome = "Banco da China Brasil S.A.", Ativo = true },
                new Banco { IdBanco = 54, Codigo = "118", Nome = "Standard Chartered Bank (Brasil) S.A.", Ativo = true },
                new Banco { IdBanco = 55, Codigo = "133", Nome = "Cresol – Sistema de Cooperativas de Crédito Rural", Ativo = true },
                new Banco { IdBanco = 56, Codigo = "136", Nome = "Unicred do Brasil", Ativo = true },
                new Banco { IdBanco = 57, Codigo = "146", Nome = "Guitta Corretora de Câmbio S.A.", Ativo = true },
                new Banco { IdBanco = 58, Codigo = "149", Nome = "Facta Financeira S.A.", Ativo = true },
                new Banco { IdBanco = 59, Codigo = "157", Nome = "Icatu Seguros S.A.", Ativo = true },
                new Banco { IdBanco = 60, Codigo = "163", Nome = "Commerzbank Brasil S.A.", Ativo = true },
                new Banco { IdBanco = 61, Codigo = "169", Nome = "Banco Olé Consignado S.A.", Ativo = true },
                new Banco { IdBanco = 62, Codigo = "182", Nome = "Dacasa Financeira S.A.", Ativo = true },
                new Banco { IdBanco = 63, Codigo = "273", Nome = "Banco Alfa de Investimento S.A.", Ativo = true },
                new Banco { IdBanco = 64, Codigo = "300", Nome = "Banco de la Nacion Argentina", Ativo = true },
                new Banco { IdBanco = 65, Codigo = "318", Nome = "Banco BMG S.A.", Ativo = true },
                new Banco { IdBanco = 66, Codigo = "321", Nome = "Credi-SIS – Sistema de Cooperativas de Crédito Noroeste", Ativo = true },
                new Banco { IdBanco = 67, Codigo = "336", Nome = "Banco C6 S.A.", Ativo = true },
                new Banco { IdBanco = 68, Codigo = "341", Nome = "Itaú Unibanco S.A.", Ativo = true },
                new Banco { IdBanco = 69, Codigo = "366", Nome = "Banco Société Générale Brasil", Ativo = true },
                new Banco { IdBanco = 70, Codigo = "370", Nome = "Banco Mizuho do Brasil S.A.", Ativo = true },
                new Banco { IdBanco = 71, Codigo = "376", Nome = "Banco J. P. Morgan S.A.", Ativo = true },
                new Banco { IdBanco = 72, Codigo = "389", Nome = "Banco Mercantil do Brasil S.A.", Ativo = true },
                new Banco { IdBanco = 73, Codigo = "394", Nome = "Banco Bradesco Financiamentos S.A.", Ativo = true },
                new Banco { IdBanco = 74, Codigo = "399", Nome = "HSBC Bank Brasil S.A.", Ativo = true },
                new Banco { IdBanco = 75, Codigo = "412", Nome = "Banco Capital S.A.", Ativo = true },
                new Banco { IdBanco = 76, Codigo = "422", Nome = "Banco Safra S.A.", Ativo = true },
                new Banco { IdBanco = 77, Codigo = "456", Nome = "Banco MUFG Brasil S.A.", Ativo = true },
                new Banco { IdBanco = 78, Codigo = "464", Nome = "Banco Sumitomo Mitsui Brasileiro S.A.", Ativo = true },
                new Banco { IdBanco = 79, Codigo = "473", Nome = "Banco Caixa Geral Brasil", Ativo = true },
                new Banco { IdBanco = 80, Codigo = "477", Nome = "Citibank N.A.", Ativo = true },
                new Banco { IdBanco = 81, Codigo = "479", Nome = "Banco ItaúBank S.A.", Ativo = true },
                new Banco { IdBanco = 82, Codigo = "487", Nome = "Deutsche Bank S.A.", Ativo = true },
                new Banco { IdBanco = 83, Codigo = "488", Nome = "JPMorgan Chase Bank", Ativo = true },
                new Banco { IdBanco = 84, Codigo = "492", Nome = "ING Bank N.V.", Ativo = true },
                new Banco { IdBanco = 85, Codigo = "505", Nome = "Credit Suisse Hedging-Griffo S.A.", Ativo = true },
                new Banco { IdBanco = 86, Codigo = "545", Nome = "Senso Corretora S.A.", Ativo = true },
                new Banco { IdBanco = 87, Codigo = "604", Nome = "Banco Industrial do Brasil S.A.", Ativo = true },
                new Banco { IdBanco = 88, Codigo = "610", Nome = "Banco VR S.A.", Ativo = true },
                new Banco { IdBanco = 89, Codigo = "611", Nome = "Banco Paulista S.A.", Ativo = true },
                new Banco { IdBanco = 90, Codigo = "612", Nome = "Banco Guanabara S.A.", Ativo = true },
                new Banco { IdBanco = 91, Codigo = "613", Nome = "Omni Banco S.A.", Ativo = true },
                new Banco { IdBanco = 92, Codigo = "623", Nome = "Banco PAN S.A.", Ativo = true },
                new Banco { IdBanco = 93, Codigo = "626", Nome = "Banco Ficsa S.A.", Ativo = true },
                new Banco { IdBanco = 94, Codigo = "630", Nome = "Smartbank S.A.", Ativo = true },
                new Banco { IdBanco = 95, Codigo = "633", Nome = "Banco Rendimento S.A.", Ativo = true },
                new Banco { IdBanco = 96, Codigo = "634", Nome = "Banco Triângulo S.A. (Tribanco)", Ativo = true },
                new Banco { IdBanco = 97, Codigo = "637", Nome = "Banco Sofisa S.A.", Ativo = true },
                new Banco { IdBanco = 98, Codigo = "641", Nome = "Banco Alvorada S.A.", Ativo = true },
                new Banco { IdBanco = 99, Codigo = "643", Nome = "Banco Pine S.A.", Ativo = true },
                new Banco { IdBanco = 100, Codigo = "652", Nome = "Itaú Unibanco Holding S.A.", Ativo = true },

                // A partir daqui, instituições sem COMPE (SCD/SCEP/Fintechs)
                new Banco { IdBanco = 101, Codigo = "", Nome = "PagSeguro Internet S.A.", Ativo = true },
                new Banco { IdBanco = 102, Codigo = "", Nome = "Mercado Pago – MP Agregador", Ativo = true },
                new Banco { IdBanco = 103, Codigo = "", Nome = "PagBank - Serviços Digitais", Ativo = true },
                new Banco { IdBanco = 104, Codigo = "", Nome = "PicPay Bank S.A.", Ativo = true },
                new Banco { IdBanco = 105, Codigo = "", Nome = "Will Bank S.A.", Ativo = true },
                new Banco { IdBanco = 106, Codigo = "", Nome = "Banco Voiter S.A.", Ativo = true },
                new Banco { IdBanco = 107, Codigo = "", Nome = "Banco Bari S.A.", Ativo = true },
                new Banco { IdBanco = 108, Codigo = "", Nome = "Banco Master S.A.", Ativo = true },
                new Banco { IdBanco = 109, Codigo = "", Nome = "Creditas SCD S.A.", Ativo = true },
                new Banco { IdBanco = 110, Codigo = "", Nome = "N26 Bank Brasil S.A.", Ativo = true },
                new Banco { IdBanco = 111, Codigo = "", Nome = "Banco BS2 S.A.", Ativo = true },
                new Banco { IdBanco = 112, Codigo = "", Nome = "Next (Bradesco)", Ativo = true },
                new Banco { IdBanco = 114, Codigo = "", Nome = "ItuBank S.A.", Ativo = true },
                new Banco { IdBanco = 115, Codigo = "", Nome = "Ubook Bank S.A.", Ativo = true },
                new Banco { IdBanco = 116, Codigo = "", Nome = "AgZero Bank (Safra)", Ativo = true },
                new Banco { IdBanco = 117, Codigo = "", Nome = "Banco A55 S.A.", Ativo = true },
                new Banco { IdBanco = 118, Codigo = "", Nome = "Juno Bank S.C.D.", Ativo = true },
                new Banco { IdBanco = 119, Codigo = "", Nome = "Celcoin Instituição de Pagamento", Ativo = true },
                new Banco { IdBanco = 120, Codigo = "", Nome = "Asaas IP S.A.", Ativo = true },
                new Banco { IdBanco = 121, Codigo = "", Nome = "Gerencianet Pagamentos S.A.", Ativo = true },
                new Banco { IdBanco = 122, Codigo = "", Nome = "Koin SCD S.A.", Ativo = true },
                new Banco { IdBanco = 123, Codigo = "", Nome = "WeBank Brasil", Ativo = true },
                new Banco { IdBanco = 124, Codigo = "", Nome = "CredCesta – Financeira", Ativo = true },
                new Banco { IdBanco = 125, Codigo = "", Nome = "Banco Letsbank S.A.", Ativo = true }
            );
        }
    }
}
